apiVersion: v1
kind: Pod
metadata:
  name: bridgy-debug
  labels:
    app: bridgy-debug
spec:
  containers:
  - name: bridgy-debug
    image: image-registry.openshift-image-registry.svc:5000/demo1/bridgy-main:latest
    command: ["/bin/sleep", "3600"]
    env:
      - name: NEXUS_DASHBOARD_URL
        valueFrom:
          secretKeyRef:
            key: nexus-dashboard-url
            name: bridgy-secrets
      - name: NEXUS_DASHBOARD_USERNAME
        valueFrom:
          secretKeyRef:
            key: nexus-dashboard-username
            name: bridgy-secrets
      - name: NEXUS_DASHBOARD_PASSWORD
        valueFrom:
          secretKeyRef:
            key: nexus-dashboard-password
            name: bridgy-secrets
      - name: NEXUS_DASHBOARD_DOMAIN
        valueFrom:
          secretKeyRef:
            key: nexus-dashboard-domain
            name: bridgy-secrets
      - name: INTERSIGHT_API_KEY
        valueFrom:
          secretKeyRef:
            key: intersight-api-key
            name: bridgy-secrets
      - name: INTERSIGHT_SECRET_KEY_PATH
        value: /etc/intersight/intersight.pem
      - name: OLLAMA_API_URL
        valueFrom:
          secretKeyRef:
            key: ollama-api-url
            name: bridgy-secrets
      - name: DEFAULT_MODEL
        valueFrom:
          secretKeyRef:
            key: default-model
            name: bridgy-secrets
      - name: LLM_BASE_URL
        valueFrom:
          secretKeyRef:
            key: llm-base-url
            name: bridgy-secrets
      - name: LLM_API_KEY
        valueFrom:
          secretKeyRef:
            key: llm-api-key
            name: bridgy-secrets
      - name: LLM_MODEL_PATH
        valueFrom:
          secretKeyRef:
            key: llm-model-path
            name: bridgy-secrets
      - name: LANGSMITH_ENDPOINT
        valueFrom:
          secretKeyRef:
            key: langsmith-endpoint
            name: bridgy-secrets
      - name: LANGSMITH_API_KEY
        valueFrom:
          secretKeyRef:
            key: langsmith-api-key
            name: bridgy-secrets
      - name: LANGSMITH_PROJECT
        valueFrom:
          secretKeyRef:
            key: langsmith-project
            name: bridgy-secrets
      - name: LANGSMITH_TRACING
        value: "true"
      - name: OLLAMA_HOME
        value: /app/.ollama
    volumeMounts:
      - mountPath: /config
        name: config-volume
      - mountPath: /app/bridgy-main/config
        name: configmap-volume
      - mountPath: /etc/intersight
        name: intersight-secret
        readOnly: true
  volumes:
    - name: config-volume
      persistentVolumeClaim:
        claimName: bridgy-main-claim0
    - configMap:
        name: bridgy-main-cm1
      name: configmap-volume
    - name: intersight-secret
      secret:
        items:
          - key: intersight-secret-key
            path: intersight.pem
        secretName: bridgy-secrets
