apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bridgy.fullname" . }}
  labels:
    {{- include "bridgy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bridgy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bridgy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bridgy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          command: ["/bin/bash"]
          args: ["/app/entrypoint.sh"]
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.environment }}
            {{- if ne $key "secure" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.environment.secure }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "bridgy.fullname" $ }}-secrets
                  key: {{ $key }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /root/.ollama
            - name: intersight-key
              mountPath: /app/bridgy-main/intersight.pem
              subPath: intersight.pem
            {{- if .Values.ssl.enabled }}
            - name: ssl-certs
              mountPath: /app/bridgy-main/cert.pem
              subPath: cert.pem
            - name: ssl-certs
              mountPath: /app/bridgy-main/key.pem
              subPath: key.pem
            {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "bridgy.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: intersight-key
          secret:
            secretName: {{ include "bridgy.fullname" . }}-intersight-key
            defaultMode: 0600
        {{- if .Values.ssl.enabled }}
        - name: ssl-certs
          secret:
            secretName: {{ include "bridgy.fullname" . }}-ssl
            defaultMode: 0600
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
