apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: bridgy-api
  name: bridgy-api
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: bridgy-api
      name: latest
      referencePolicy:
        type: ""
