apiVersion: v1
kind: Secret
metadata:
  name: bridgy-secrets
  labels:
    app: bridgy
type: Opaque
stringData:
  # Nexus Dashboard credentials
  nexus-dashboard-url: "https://your-nexus-dashboard-url"
  nexus-dashboard-username: "your_username"
  nexus-dashboard-password: "your_password"
  nexus-dashboard-domain: "local"
  
  # Intersight API credentials
  intersight-api-key: "your_intersight_api_key_here"
  # Note: For the secret key, you'll need to mount this as a file or use a different approach
  # For now, we're including it as a string value but consider mounting as a file in production
  intersight-secret-key: "your_base64_encoded_secret_key_here"
  
  # LLM Configuration
  ollama-api-url: "http://localhost:11434/api/chat"
  default-model: "gemma2"
  
  # Remote LLM Service
  llm-base-url: "http://64.101.169.102:8000/v1"
  llm-api-key: "llm-api-key"
  llm-model-path: "/ai/models/Meta-Llama-3-8B-Instruct/"
  
  # LangSmith Configuration
  langsmith-endpoint: "https://api.smith.langchain.com"
  langsmith-api-key: "your_langsmith_api_key_here"
  langsmith-project: "bridgy"
