apiVersion: v1
kind: ConfigMap
metadata:
  name: bridgy-api-cm1
  labels:
    io.kompose.service: bridgy-api
data:
  Dockerfile: |
    # Use standard Python image
    FROM python:3.10-slim

    WORKDIR /app

    # Install build dependencies
    RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        gcc \
        python3-dev && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

    # Copy requirements file first (for better layer caching)
    COPY ./requirements.txt /app/requirements.txt

    # Install dependencies
    RUN pip install --no-cache-dir -r /app/requirements.txt

    # Copy application code
    COPY ./bridgy-api /app/bridgy-api

    # Create a non-root user for security
    RUN adduser --disabled-password --gecos "" appuser && \
        chown -R appuser:appuser /app

    # Switch to non-root user
    USER appuser

    # Set Python environment variables
    ENV PYTHONDONTWRITEBYTECODE=1 \
        PYTHONUNBUFFERED=1

    # Expose port for API
    EXPOSE 5000

    # Command to run the application
    CMD ["python", "-m", "uvicorn", "bridgy-api.main:app", "--host", "0.0.0.0", "--port", "5000"]
  requirements.txt: |
    fastapi
    uvicorn[standard]
    pydantic
    python-dotenv
    httpx
