apiVersion: v1
kind: Secret
metadata:
  name: bridgy-secrets
  labels:
    app: bridgy
type: Opaque
stringData:
  langsmith-endpoint: "https://api.smith.langchain.com"
  langsmith-api-key: "YOUR_LANGSMITH_API_KEY_HERE"
  langsmith-project: "bridgyv2"
  intersight-api-key: "YOUR_INTERSIGHT_API_KEY_HERE"
  intersight-secret-key-path: "/var/bridgy/backend/bridgy-intersight-llm-demo/intersight.pem"
  nexus-dashboard-url: "https://YOUR_NEXUS_DASHBOARD_URL/"
  nexus-dashboard-username: "YOUR_USERNAME"
  nexus-dashboard-password: "YOUR_PASSWORD"
  nexus-dashboard-domain: "local"
  hf-token: "YOUR_HUGGING_FACE_TOKEN_HERE"
  tensor-parallel-size: "1"
  intersight-secret-key: |
    -----BEGIN EC PRIVATE KEY-----
    YOUR_PRIVATE_KEY_CONTENT_HERE
    -----END EC PRIVATE KEY-----
