apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bridgy-api
  name: bridgy-api
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: bridgy-api
