apiVersion: v1
kind: ConfigMap
metadata:
  name: bridgy-main-env
  labels:
    app: bridgy-main
data:
  # Remote LLM Service Configuration
  LLM_BASE_URL: "http://64.101.169.102:8000/v1"
  LLM_MODEL: "/ai/models/Meta-Llama-3-8B-Instruct/"
  LLM_API_KEY: "your_llm_api_key_here"
  
  # LangSmith Configuration
  LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  LANGSMITH_API_KEY: "your_langsmith_api_key_here"
  LANGSMITH_PROJECT: "your_project_name"
  
  # Intersight Configuration
  INTERSIGHT_API_KEY: "your_intersight_api_key_here"
  INTERSIGHT_SECRET_KEY_PATH: "/path/to/your/intersight.pem"
  
  # Nexus Dashboard Configuration
  NEXUS_DASHBOARD_URL: "https://your.nexus.dashboard.url/"
  NEXUS_DASHBOARD_USERNAME: "your_username"
  NEXUS_DASHBOARD_PASSWORD: "your_password"
  NEXUS_DASHBOARD_DOMAIN: "your_domain"
  
  # MongoDB Configuration
  MONGO_ENABLED: "true"
  MONGODB_URL: "mongodb://bridgy:bridgy123@mongodb:27017/bridgy_db"
  MONGODB_DB: "bridgy_db"
