apiVersion: v1
kind: ConfigMap
metadata:
  name: bridgy-api-cm1
  labels:
    io.kompose.service: bridgy-api
data:
  Dockerfile: |-
    # Use standard Python image
    FROM python:3.10-slim

    # Set working directory
    WORKDIR /app

    # Install system dependencies
    RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        && \
        rm -rf /var/lib/apt/lists/*

    # Create requirements file directly using multiple RUN commands to avoid YAML issues
    RUN echo 'fastapi' > /app/requirements.txt
    RUN echo 'uvicorn[standard]' >> /app/requirements.txt
    RUN echo 'pydantic' >> /app/requirements.txt
    RUN echo 'python-dotenv' >> /app/requirements.txt
    RUN echo 'httpx' >> /app/requirements.txt

    # Install dependencies
    RUN pip install --no-cache-dir -r /app/requirements.txt

    # Create directories for application
    RUN mkdir -p /app/bridgy-api

    # Note: Source code for the API must be provided during OpenShift binary build
    # Use: oc start-build bridgy-api --from-dir=./bridgy-api

    # Set environment variables for Python
    ENV PYTHONDONTWRITEBYTECODE=1
    ENV PYTHONUNBUFFERED=1

    # Expose port 5000 for the API
    EXPOSE 5000

    # Start the app
    CMD ["uvicorn", "bridgy-api.main:app", "--host", "0.0.0.0", "--port", "5000"]
