apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: bridgy-main
  name: bridgy-main
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: bridgy-main
      name: latest
      referencePolicy:
        type: ""
