apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bridgy-main
  labels:
    io.kompose.service: bridgy-main
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: bridgy-main
    weight: 100
  wildcardPolicy: None
