apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bridgy-main
  labels:
    app: bridgy-main
    io.kompose.service: bridgy-main
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: DockerImage
        name: ubuntu:22.04
  configMaps:
    - configMap:
        name: bridgy-main-cm1
      env:
        - name: NEXUS_DASHBOARD_URL
          valueFrom:
            secretKeyRef:
              name: bridgy-secrets
              key: nexus-dashboard-url
              optional: true
        - name: NEXUS_DASHBOARD_USERNAME
          valueFrom:
            secretKeyRef:
              name: bridgy-secrets
              key: nexus-dashboard-username
              optional: true
        - name: NEXUS_DASHBOARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bridgy-secrets
              key: nexus-dashboard-password
              optional: true
  output:
    to:
      kind: ImageStreamTag
      name: bridgy-main:latest
  resources:
    limits:
      memory: 4Gi
      cpu: 2
    requests:
      memory: 2Gi
      cpu: 1
  completionDeadlineSeconds: 1800  # 30 minutes build timeout
