apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  labels:
    app: mongodb
data:
  init-mongo.js: |
    db = db.getSiblingDB('admin');
    
    // Create the bridgy user with the correct password and roles
    db.createUser({
      user: 'bridgy',
      pwd: 'bridgy123',
      roles: [
        { role: 'readWrite', db: 'bridgy_db' },
        { role: 'dbAdmin', db: 'bridgy_db' }
      ]
    });
    
    db = db.getSiblingDB('bridgy_db');
    
    // Create a test collection to verify database exists
    db.createCollection('sessions');
    db.sessions.insert({ name: 'initialization', status: 'completed', timestamp: new Date() });
