kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-anyuid
  labels:
    app: mongodb
subjects:
  - kind: ServiceAccount
    name: mongodb
    namespace: demo1
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
