apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  mongod.conf: |
    # mongod.conf
    
    # Where and how to store data.
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    
    # where to write logging data
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    
    # network interfaces
    net:
      port: 27017
      bindIp: 0.0.0.0
    
    # security
    security:
      authorization: disabled
  init-mongo.js: |
    // This script will run automatically when MongoDB starts
    print('Initializing MongoDB for Bridgy application without authentication...');
    
    // Create and initialize the bridgy_db database
    db = db.getSiblingDB('bridgy_db');
    db.createCollection('sessions');
    db.sessions.insert({ name: 'initialization', status: 'completed', timestamp: new Date() });
    
    print('MongoDB initialization complete!');
