apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
    io.kompose.service: mongodb-data
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi
  # Add explicit volume name to bind to the available PV
  volumeName: demo1-pv2
