apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  labels:
    app: mongodb
data:
  init-mongo.js: |
    // This script will run automatically when MongoDB starts
    print('Initializing MongoDB for Bridgy application without authentication...');
    
    // Create and initialize the bridgy_db database
    db = db.getSiblingDB('bridgy_db');
    db.createCollection('sessions');
    db.sessions.insert({ name: 'initialization', status: 'completed', timestamp: new Date() });
    
    print('MongoDB initialization complete!');
    
