apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  labels:
    app: vllm-server
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
