apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sa
  labels:
    app: vllm-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-role
  labels:
    app: vllm-server
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "pods"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-rolebinding
  labels:
    app: vllm-server
subjects:
- kind: ServiceAccount
  name: vllm-sa
roleRef:
  kind: Role
  name: vllm-role
  apiGroup: rbac.authorization.k8s.io
