apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bridgy-main
  name: bridgy-main
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: bridgy-main
