apiVersion: v1
kind: Pod
metadata:
  name: bridgy-debug
spec:
  containers:
  - name: bridgy-debug
    image: image-registry.openshift-image-registry.svc:5000/demo1/bridgy-main:latest
    command: ["sleep", "3600"]
    env:
    - name: MONGODB_URL
      value: "mongodb://bridgy:bridgy123@mongodb:27017/bridgy_db?authSource=admin"
    - name: LLM_BASE_URL
      value: "http://64.101.169.102:8000/v1"
    - name: LLM_MODEL
      value: "/ai/models/Meta-Llama-3-8B-Instruct/"
    - name: LLM_API_KEY
      value: "llm-api-key"
  restartPolicy: Never
