apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-huggingface
  labels:
    app: vllm-server
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
